# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ErlangInsect2Shift <- function(t, y, params) {
    .Call('_VART_ErlangInsect2Shift', PACKAGE = 'VART', t, y, params)
}

ErlangInsectSimple <- function(t, y, params) {
    .Call('_VART_ErlangInsectSimple', PACKAGE = 'VART', t, y, params)
}

ErlangInsect_Spray <- function(t, y, params) {
    .Call('_VART_ErlangInsect_Spray', PACKAGE = 'VART', t, y, params)
}

ErlangInsect_Shift <- function(t, y, params) {
    .Call('_VART_ErlangInsect_Shift', PACKAGE = 'VART', t, y, params)
}

