
#' Model the pesticide spraying of a single species emergence as well as determining
#' the number of sprays needed
#'
#' @param list_params_init The parameters generated by the params_creator (a list with two elements)
#' including the initial conditions and parameters
#' @param AT The action threshold to spray for each shape
#'
#' @return A dataframe that contains the outputs as well as the number of spray times
#' @export
#'
#' @examples ss_shape_spray_dynamics(list_params, 100)
ss_shape_spray_dynamics <- function(list_params_init, AT = NA){

        #run it for 200 days
        times  <- seq(0, 100, 1/10)
        x_int_interest <- list_params_init[[1]] # the initial values
        param_int_interest <- list_params_init[[2]] # the parameters


        if (is.na(AT) == TRUE){
        AT_Val <- list_params_init[[3]]
        }else{
        AT_Val <- AT
        }

        ###This is the function that figures out when the abundance
        ###reaches the action threshold-(the root)
        rootFun_Spray_D <- function (t, y, parms) {

                n <- parms['n'] #need the shape parameter

                threshold <-  AT_Val

                yroot<-vector(len=1) #a weird gimmick

                yroot[1] <- y[n+1] - threshold

                return(yroot)
        }

        # and what to do when you hit the root
        # add events = list(func=eventfun, root = TRUE) to lsodar
        eventfun_D<- function(t,y, parms) {
                n <- parms['n']

                y[n+1] <- y[n+1] - 1e-10# to make sure there's no doubling of threshold crossing -- sloppy hack

                y[n+2] <- y[n+2] +1

                return(y)
        }

        ###This runs the desolve WITH root and event
        output0 <- lsodar(
                y = x_int_interest ,
                times = seq(0,100,1/10),
                func = ErlangInsect_Spray,
                parms = param_int_interest,
                rootfun= rootFun_Spray_D,
                rtol = 1e-4,
                atol = 1e-6,
                events = list(func = eventfun_D,
                              root = TRUE))

        days_of_sprays <- length(attributes(output0)$troot)
        output_dynamics_S2 <- data.frame(output0)[,c("time", "S2")]
        output_dynamics_S2$days_of_spray <-  length(attributes(output0)$troot)
        output_dynamics_S2$shape <- param_int_interest[['n']]


       list_dynamics_frequency <- list(output_dynamics_S2,
            cbind(days_of_sprays,param_int_interest[['n']]))

        return(list_dynamics_frequency )
}
